name: Build project with Maven
on:
  workflow_dispatch:
  pull_request:
  schedule:
  - cron: '2 2 * * 1-5' # run nightly master builds on weekdays

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5 # pin@v2
    - name: Java setup
      uses: actions/setup-java@v4 # pin@v1
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven
    - name: Run Maven
      run: mvn -B clean verify com.mycila:license-maven-plugin:check
